server_connect_timeout: 5000
enforce_secure_profile: false
forge_support: false
player_limit: -1
log_pings: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  void_lobby:
    motd: '&1Just another BungeeCord - Void - Forced Host'
    address: 0.0.0.0:25565
    restricted: false
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 0.0.0.0:25566
    restricted: false
listeners:
- query_port: 25564
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - void_lobby
  bind_local_address: true
  host: 0.0.0.0:25564
  max_players: 60
  tab_size: 60
  force_default_server: true
ip_forward: true
remote_ping_timeout: 5000
reject_transfers: false
remote_ping_cache: -1
connection_throttle: 4000
stats: 5422c226-b212-49f4-9415-b23681bac5de
connection_throttle_limit: 3
groups:
  md_5:
  - admin
prevent_proxy_connections: false
